theme: jekyll-theme-minimal
title: [Maria Elena Villalobos Ponte]
description: [Hi! I am a Data Scientist with a Computer Science backgroud helping businesses solve real-world business problems with data.]
